# Generated by Django 3.2.4 on 2022-07-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('birth', models.CharField(default='', max_length=10)),
                ('tmi', models.CharField(default='', max_length=100)),
                ('image_link', models.CharField(max_length=100)),
            ],
        ),
    ]
