# Generated by Django 3.2.4 on 2022-07-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('birth', models.CharField(default='', max_length=10)),
                ('tmi', models.CharField(default='', max_length=100)),
                ('image_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelLink',
            fields=[
                ('model_id', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.member')),
                ('glow_config', models.CharField(default='', max_length=100)),
                ('glow_pth', models.CharField(default='', max_length=100)),
                ('hifi_config', models.CharField(default='', max_length=100)),
                ('hifi_pth', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
