# Generated by Django 3.2.4 on 2022-07-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_modellink_model_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modellink',
            old_name='model_id',
            new_name='id',
        ),
    ]
