version: "3"

services:
  frontend:
    build:
      # context : 현재 폴더의 frontend 폴더에 있는 도커파일을 쓰겠다.
      context: ./frontend
   # command : 컨테이너가 띄워질 때 실행하는 명령어 / 서버실행
    command: [ "yarn", "start" ] 
    ports:
    # 왼쪽이 도커 바깥(외부에서 접근할 포트번호) / 오른쪽이 도커 내부(컨테이너 내부)
      - 3000:3000
    volumes:
      # 왼쪽이 우리 컴퓨터, 오른쪽이 도커 컨테이너
      # 리눅스 컨테이너의 프론트엔드 폴더에 우리 컴퓨터의 프론트엔드 폴더를 공유하겠다.
      # 서로 바뀐 부분 적용됨
      - ./frontend/:/frontend
      - ./frontend/node_modules/:/frontend/node_modules
    
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:5000
    tty: true