# Generated by Django 3.2.4 on 2022-08-04 06:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('birth', models.CharField(max_length=10)),
                ('tmi', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('github_link', models.CharField(default='', max_length=100)),
                ('image_link', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelLink',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainApp.member')),
                ('glow_config', models.CharField(default='', max_length=100)),
                ('glow_pth', models.CharField(default='', max_length=100)),
                ('glow_scale_stats', models.CharField(default='', max_length=100)),
                ('hifi_config', models.CharField(default='', max_length=100)),
                ('hifi_pth', models.CharField(default='', max_length=100)),
                ('hifi_scale_stats', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=100)),
                ('text', models.CharField(default='', max_length=100)),
                ('created_at', models.CharField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_id', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='mainApp.member')),
            ],
        ),
    ]
