# Generated by Django 3.2.4 on 2022-07-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellink',
            name='g_scale_stats',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modellink',
            name='h_scale_stats',
            field=models.CharField(default='', max_length=100),
        ),
    ]
