# Generated by Django 3.2.4 on 2022-07-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20220725_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='modellink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='modellink',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='text',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='text',
            name='updated_at',
        ),
    ]
