# Generated by Django 3.2.4 on 2022-07-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20220725_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modellink',
            old_name='g_scale_stats',
            new_name='glow_scale_stats',
        ),
        migrations.RenameField(
            model_name='modellink',
            old_name='h_scale_stats',
            new_name='hifi_scale_stats',
        ),
    ]
