# Generated by Django 3.2.4 on 2022-07-21 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('birth', models.CharField(default='', max_length=10)),
                ('tmi', models.CharField(default='', max_length=100)),
                ('image_link', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelLink',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainApp.member')),
                ('glow_config', models.CharField(default='', max_length=100)),
                ('glow_pth', models.CharField(default='', max_length=100)),
                ('hifi_config', models.CharField(default='', max_length=100)),
                ('hifi_pth', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('text_id', models.ForeignKey(db_column='text_id', on_delete=django.db.models.deletion.CASCADE, to='mainApp.member')),
            ],
        ),
    ]
