# Generated by Django 3.2.4 on 2022-07-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('birth', models.CharField(max_length=10)),
                ('tmi', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='model_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glow_config', models.CharField(max_length=100)),
                ('glow_pth', models.CharField(max_length=100)),
                ('hifi_config', models.CharField(max_length=100)),
                ('hifi_pth', models.CharField(max_length=100)),
                ('_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.member')),
            ],
        ),
    ]
