# Generated by Django 3.2.4 on 2022-07-21 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='text_id',
        ),
        migrations.AlterField(
            model_name='modellink',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainApp.member'),
        ),
        migrations.AlterField(
            model_name='text',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainApp.member'),
        ),
    ]
